# Generated by Django 5.2.4 on 2025-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('meal_left', models.IntegerField(default=60)),
                ('daily_scan_count', models.IntegerField(default=2)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
